let colors = {
  transparent: "transparent",
  "fl-primary": "#1d3740",
  "fl-primary-alternate": "#A83723",
  "fl-primary-accent": "#BDD6D7",
  "fl-secondary": "#77878C",
  "fl-secondary-alternate": "#BDD6D7",
  "fl-secondary-accent": "#E5EFEF",
  "fl-secondary-accent-alternate": "#F0D5CA",
  black: "#22292f",
  "grey-darkest": "#3d4852",
  "grey-darker": "#606f7b",
  "grey-dark": "#8795a1",
  grey: "#b8c2cc",
  "grey-light": "#dae1e7",
  "grey-lighter": "#f1f5f8",
  "grey-lightest": "#f8fafc",
  white: "#ffffff",

  "red-darkest": "#3b0d0c",
  "red-darker": "#621b18",
  "red-dark": "#cc1f1a",
  red: "#e3342f",
  "red-light": "#ef5753",
  "red-lighter": "#f9acaa",
  "red-lightest": "#fcebea",

  "orange-darkest": "#462a16",
  "orange-darker": "#613b1f",
  "orange-dark": "#de751f",
  orange: "#f6993f",
  "orange-light": "#faad63",
  "orange-lighter": "#fcd9b6",
  "orange-lightest": "#fff5eb",

  "yellow-darkest": "#453411",
  "yellow-darker": "#684f1d",
  "yellow-dark": "#f2d024",
  yellow: "#ffed4a",
  "yellow-light": "#fff382",
  "yellow-lighter": "#fff9c2",
  "yellow-lightest": "#fcfbeb",

  "green-darkest": "#0f2f21",
  "green-darker": "#1a4731",
  "green-dark": "#1f9d55",
  green: "#70A999", // customized for finiteloop
  "green-light": "#70A999",
  "green-lighter": "#70A999",
  "green-lightest": "#70A999",

  "teal-darkest": "#0d3331",
  "teal-darker": "#20504f",
  "teal-dark": "#38a89d",
  teal: "#70A999", // customized for finiteloop
  "teal-light": "#64d5ca",
  "teal-lighter": "#a0f0ed",
  "teal-lightest": "#e8fffe",

  "blue-darkest": "#12283a",
  "blue-darker": "#1c3d5a",
  "blue-dark": "#2779bd",
  blue: "#3490dc",
  "blue-light": "#6cb2eb",
  "blue-lighter": "#bcdefa",
  "blue-lightest": "#eff8ff",

  "indigo-darkest": "#191e38",
  "indigo-darker": "#2f365f",
  "indigo-dark": "#5661b3",
  indigo: "#6574cd",
  "indigo-light": "#7886d7",
  "indigo-lighter": "#b2b7ff",
  "indigo-lightest": "#e6e8ff",

  "purple-darkest": "#21183c",
  "purple-darker": "#382b5f",
  "purple-dark": "#794acf",
  purple: "#9561e2",
  "purple-light": "#a779e9",
  "purple-lighter": "#d6bbfc",
  "purple-lightest": "#f3ebff",

  "pink-darkest": "#451225",
  "pink-darker": "#6f213f",
  "pink-dark": "#eb5286",
  pink: "#f66d9b",
  "pink-light": "#fa7ea8",
  "pink-lighter": "#ffbbca",
  "pink-lightest": "#ffebef",
}

module.exports = {
  future: {
    removeDeprecatedGapUtilities: true,
    purgeLayersByDefault: true,
  },
  purge: [],
  theme: {
    screens: {
      sm: "210px",
      md: "768px",
      lg: "992px",
      xl: "1200px",
    },
    fontFamily: {
      neptune: [
        "Neptune-Light",
        "Neptune-Regular",
        "system-ui",
        "BlinkMacSystemFont",
        "-apple-system",
        "Segoe UI",
        "Roboto",
        "Oxygen",
        "Ubuntu",
        "Cantarell",
        "Fira Sans",
        "Droid Sans",
        "Helvetica Neue",
        "sans-serif",
      ],
      sans: [
        "Open Sans",
        "system-ui",
        "BlinkMacSystemFont",
        "-apple-system",
        "Segoe UI",
        "Roboto",
        "Oxygen",
        "Ubuntu",
        "Cantarell",
        "Fira Sans",
        "Droid Sans",
        "Helvetica Neue",
        "sans-serif",
      ],
      serif: [
        "Constantia",
        "Lucida Bright",
        "Lucidabright",
        "Lucida Serif",
        "Lucida",
        "DejaVu Serif",
        "Bitstream Vera Serif",
        "Liberation Serif",
        "Georgia",
        "serif",
      ],
      mono: [
        "Menlo",
        "Monaco",
        "Consolas",
        "Liberation Mono",
        "Courier New",
        "monospace",
      ],
    },

    boxShadow: {
      flPrimary: "inset 0 5px 0 0 #ba4f1a",
      default: "0 2px 4px 0 rgba(0,0,0,0.10)",
      sm: "0 2px 4px 0 rgba(0,0,0,0.12), 0 2px 4px 0 rgba(0,0,0,0.08)",
      md: "0 4px 8px 0 rgba(0,0,0,0.12), 0 2px 4px 0 rgba(0,0,0,0.08)",
      lg: "0 15px 30px 0 rgba(0,0,0,0.11), 0 5px 15px 0 rgba(0,0,0,0.08)",
      inner: "inset 0 2px 4px 0 rgba(0,0,0,0.06)",
      outline: "0 0 0 3px rgba(52,144,220,0.5)",
      none: "none",
    },

    extend: {
      height: {
        half: "50vh",
        quarter: "25vh",
        thirty: "30vh",
        thirtyfive: "35vh",
        forty: "40vh",
        auto: "auto",
        px: "1px",
        1: "0.25rem",
        2: "0.5rem",
        3: "0.75rem",
        4: "1rem",
        5: "1.25rem",
        6: "1.5rem",
        8: "2rem",
        10: "2.5rem",
        12: "3rem",
        16: "4rem",
        24: "6rem",
        32: "8rem",
        48: "12rem",
        64: "16rem",
        full: "100%",
        screen: "100vh",
      },
      maxWidth: {
        "screen-2lg": "1200px",
        xs: "20rem",
        sm: "30rem",
        md: "40rem",
        lg: "50rem",
        xl: "60rem",
        "2xl": "70rem",
        "3xl": "80rem",
        "4xl": "90rem",
        "5xl": "100rem",
        "1/4": "10%",
        "2/4": "50%",
        "3/4": "80%",
        "4/5": "95%",
        full: "100%",
      },
      padding: {
        px: "1px",
        0: "0",
        1: "0.25rem",
        2: "0.5rem",
        3: "0.75rem",
        4: "1rem",
        5: "1.25rem",
        6: "1.5rem",
        8: "2rem",
        10: "2.5rem",
        12: "3rem",
        16: "4rem",
        20: "5rem",
        24: "6rem",
        32: "8rem",
        34: "10rem",
        38: "12rem",
      },
      margin: {
        auto: "auto",
        px: "1px",
        0: "0",
        1: "0.25rem",
        2: "0.5rem",
        3: "0.75rem",
        4: "1rem",
        5: "1.25rem",
        6: "1.5rem",
        8: "2rem",
        10: "2.5rem",
        12: "3rem",
        16: "4rem",
        20: "5rem",
        24: "6rem",
        32: "8rem",
      },

      colors: {
        transperant: colors["transparent"],
        white: colors["white"],
        "fl-primary": colors["fl-primary"],
        "fl-primary-alternate": colors["fl-primary-alternate"],
        "fl-primary-accent": colors["fl-primary-accent"],
        "fl-secondary": colors["fl-secondary"],
        "fl-secondary-alternate": colors["fl-secondary-alternate"],
        "fl-secondary-accent": colors["fl-secondary-accent"],
        "fl-secondary-accent-alternate":
          colors["fl-secondary-accent-alternate"],
      },

      textColor: {
        transperant: colors["transparent"],
        white: colors["white"],
        "fl-primary": colors["white"],
        "fl-primary-alternate": colors["white"],
        "fl-primary-accent": colors["fl-primary-accent"],
        "fl-secondary": colors["white"],
        "fl-secondary-alternate": colors["fl-secondary-alternate"],
        "fl-secondary-accent": colors["fl-secondary-accent"],
        "fl-secondary-accent-alternate":
          colors["fl-secondary-accent-alternate"],
      },

      backgroundColors: {
        transperant: colors["transparent"],
        white: colors["white"],
        "fl-primary": colors["fl-primary"],
        "fl-primary-alternate": colors["fl-primary-alternate"],
        "fl-primary-accent": colors["fl-primary-accent"],
        "fl-secondary": colors["fl-secondary"],
        "fl-secondary-alternate": colors["fl-secondary-alternate"],
        "fl-secondary-accent": colors["fl-secondary-accent"],
        "fl-secondary-accent-alternate":
          colors["fl-secondary-accent-alternate"],
      },

      borderColors: {
        default: colors["grey-light"],
        transperant: colors["transparent"],
        white: colors["white"],
        "fl-primary": colors["fl-primary"],
        "fl-primary-alternate": colors["fl-primary-alternate"],
        "fl-primary-accent": colors["fl-primary-accent"],
        "fl-secondary": colors["fl-secondary"],
        "fl-secondary-alternate": colors["fl-secondary-alternate"],
        "fl-secondary-accent": colors["fl-secondary-accent"],
        "fl-secondary-accent-alternate":
          colors["fl-secondary-accent-alternate"],
      },
    },

    inset: {
      "1/2": "50%",
      "1/5": "15%",
      "1/4": "20%",
      "1/6": "10%",
      "1/7": "5%",
      "2/8": "25%",
      "1/3": "33%",
    },
  },
  variants: {},
  plugins: [],
  corePlugins: {
    preflight: false,
  },
}
